k11 pro encoder fixed
Keychron/qmk_firmware pull request #162
Opened 2023-08-15 04:09 UTC by lalalademaxiya1

Fixed the encoder interrupter part to solve the issue that encoder does not work when the backlight is in off status.

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-08-24 06:21 UTC, lokher requested changes

2023-08-24 06:21 UTC, lokher commented on keyboards/keychron/k11_pro/k11_pro.c
> +#if defined(KC_BLUETOOTH_ENABLE) && defined(ENCODER_ENABLE)
```suggestion
#if defined(ENCODER_ENABLE)
```

2023-08-24 06:21 UTC, lokher commented on keyboards/keychron/q8_pro/q8_pro.c
>  #if defined(KC_BLUETOOTH_ENABLE) && defined(ENCODER_ENABLE)
```suggestion
#if defined(ENCODER_ENABLE)
```

2023-08-28 02:16 UTC, lalalademaxiya1 commented on keyboards/keychron/k11_pro/k11_pro.c
> +#if defined(KC_BLUETOOTH_ENABLE) && defined(ENCODER_ENABLE)
Changed

2023-08-28 02:16 UTC, lalalademaxiya1 commented on keyboards/keychron/q8_pro/q8_pro.c
>  #if defined(KC_BLUETOOTH_ENABLE) && defined(ENCODER_ENABLE)
Changed

2023-09-07 07:35 UTC, merged