Add keychron k17 pro
Keychron/qmk_firmware pull request #184
Opened 2023-10-16 03:44 UTC by lalalademaxiya1

As the title and request for a review, thanks!

## Description

- Added k17_pro/ansi_encoder rgb and white version
- Added q10_pro/ansi_encoder and q10_pro/iso_encoder
- Added q13_pro/ansi_encoder and q13_pro/iso_encoder

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-10-23 01:41 UTC, Mchh85 commented
@keychron-dev @lokher 您好，我买的q13 pro 已经到手了，我需要修改固件。什么时候在bluetooth_playground分支中合并这个啊？已经买了五天了，一直没有这个型号。

2023-10-23 14:43 UTC, lokher commented
> @keychron-dev @lokher 您好，我买的q13 pro 已经到手了，我需要修改固件。什么时候在bluetooth_playground分支中合并这个啊？已经买了五天了，一直没有这个型号。

我们最近比较忙，要晚点才能处理，你可以直接从以下分支把代码提取出来放到 `bluetooth_playgroun` 中编译
https://github.com/lalalademaxiya1/qmk_firmware/tree/keychron_k17_pro

2023-10-25 07:00 UTC, lokher requested changes

2023-10-25 07:00 UTC, lokher commented on keyboards/keychron/bluetooth/bluetooth.c
> +    /* Prevent keys from not bouncing back after shutdown due to low power */
```suggestion
    /* Release all keys before  low battery shutting down */
```

2023-10-25 07:00 UTC, lokher commented on keyboards/keychron/k17_pro/k17_pro.h
> +	NEW_SAFE_RANGE
```suggestion
	NEW_SAFE_RANGE
```
```suggestion
    NEW_SAFE_RANGE
```

2023-10-25 07:00 UTC, lokher commented on keyboards/keychron/q10_pro/ansi_encoder/ansi_encoder.c
> +/* Copyright 2022 @ Keychron (https://www.keychron.com)
```suggestion
/* Copyright 2023 @ Keychron (https://www.keychron.com)
```

2023-10-25 07:00 UTC, lokher commented on keyboards/keychron/q10_pro/ansi_encoder/config.h
> +/* Copyright 2022 @ Keychron (https://www.keychron.com)
```suggestion
/* Copyright 2023 @ Keychron (https://www.keychron.com)
```

2023-10-25 07:00 UTC, lokher commented on keyboards/keychron/q10_pro/config.h
> +/* Copyright 2022 @ Keychron(https://www.keychron.com)
```suggestion
/* Copyright 2023 @ Keychron(https://www.keychron.com)
```

2023-10-25 07:00 UTC, lokher commented on keyboards/keychron/q10_pro/iso_encoder/config.h
> +/* Copyright 2022 @ Keychron (https://www.keychron.com)
```suggestion
/* Copyright 2023 @ Keychron (https://www.keychron.com)
```

2023-10-25 07:00 UTC, lokher commented on keyboards/keychron/q10_pro/iso_encoder/iso_encoder.c
> +/* Copyright 2022 @ Keychron (https://www.keychron.com)
```suggestion
/* Copyright 2023 @ Keychron (https://www.keychron.com)
```

2023-10-25 07:00 UTC, lokher commented on keyboards/keychron/q13_pro/ansi_encoder/ansi_encoder.c
> +/* Copyright 2022 @ Keychron (https://www.keychron.com)
```suggestion
/* Copyright 2023 @ Keychron (https://www.keychron.com)
```

2023-10-25 07:00 UTC, lokher commented on keyboards/keychron/q13_pro/iso_encoder/iso_encoder.c
> +/* Copyright 2022 @ Keychron (https://www.keychron.com)
```suggestion
/* Copyright 2023 @ Keychron (https://www.keychron.com)
```

2023-11-03 09:41 UTC, lokher approved these changes

2023-12-07 21:00 UTC, campbellhennessy commented
Hello, I am wondering when this PR is planned to be merged into the bluetooth_playground branch?

2024-02-22 01:59 UTC, closed without merging